NY_Shop/NY_Shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('',include('main.urls', namespace='main')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

NY_Shop/cart/urls.py
from django.urls import path
from . import views



app_name= 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
         name='cart_remove'),
]

NY_Shop/main/urls.py
from django.urls import path
from . import views

app_name='main'

urlpatterns = [
    path('', views.popular_list, name='popular_list'),
    path('shop/', views.product_list, name='product_list'),
    
    path('shop/category/<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    path('shop/<slug:slug>/', views.product_detail,
         name='product_detail'),
               ]

NY_Shop/cart/models.py
from django.db import models

# Create your models here.

NY_Shop/main/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=20,
                            unique=True)
    slug = models.SlugField(max_length=20,
                            unique=True)
    
    
    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        
    
    def get_absolute_url(self):
        return reverse("main:product_list_by_category",
                       args=[self.slug])


    def __str__(self):
        return self.name
    
    
class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=27)
    slug = models.SlugField(max_length=50)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,
                                decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    discount = models.DecimalField(default=0.00, max_digits=4,
                                   decimal_places=2)
    
    
    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]
        

    def __str__(self):
        return self.name
    
    
    def get_absolute_url(self):
        return reverse('main:product_detail',
                       args=[self.slug])
    
    
    def sell_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount / 100, 2)
        return self.price

NY_Shop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1,16)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int
    )
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

NY_Shop/cart/views.py
from django.shortcuts import render, redirect, \
    get_object_or_404
from django.views.decorators.http import require_POST
from main.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

NY_Shop/main/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from .models import Product, Category
from cart.forms import CartAddProductForm

def popular_list(request):
    products = Product.objects.filter(available=True)[:3]
    return render(request,
                  'main/index/index.html',
                  {'products': products})
    

def product_detail(request, slug):
    product = get_object_or_404(Product,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm
    return render(request,
                  'main/product/detail.html',
                  {'product': product,
                   'cart_product_form' : cart_product_form
                   })
    
    
def product_list(request, category_slug=None):
    page = request.GET.get('page', 1)
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    paginator = Paginator(products, 8)
    current_page = paginator.page(int(page))
    if category_slug:
        category = get_object_or_404(Category,
                                     slug=category_slug)
        paginator = Paginator(products.filter(category=category), 8)
        current_page = paginator.page(int(page))
    return render(request,
                  'main/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': current_page,
                   'slug_url': category_slug})
    

NY_Shop/cart/templates/cart/detail.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Cart{% endblock title %}

{% block content %}
    <section class="cart d-flex">
        <div class="cart-title">
            <h2>Корзина</h2>
        </div>
        <div class="cart-cards">
            {% for item in cart  %}
            {% with product=item.product %}
                <div class="cart-card d-flex">
                    <div class="cart-card-img">
                        <img src="{% if product.image %}{{ product.image.url }}{% endif %}" alt="" class="detail-image" height="200" width="200">
                    </div>
                    <div class="cart-card-info">
                        <div class="cart-card-name">
                            <p>{{ product.name }}</p>
                        </div>
                        <div class="cart-card-q">
                            <p>Кол-во: {{item.quantity }} </p>
                        </div>
                    </div>

                    <form action="{% url "cart:cart_remove" product.id %}" method="post">
                        <input type="submit" value="Убрать" class="remove-btn">
                        {% csrf_token %}
                    </form>
                    <div class="cart-card-price">
                         {% if product.discount %}
                                    <div class="card-discount">
                                        <p class="line">{{ product.price }} ₽</p>
                                        <p>{{ product.sell_price }} ₽</p>
                                    </div>
                                {% else %}
                                    <p class="price">{{ product.price }} ₽</p>
                                {% endif %}
                    </div>
                </div>
            {% endwith %}
            {% endfor %}
        </div>

        <div class="total">
            <h5>Итого:   {{ cart.get_total_price }}  ₽</h5>
        </div>

        <div class="cart-buttons d-flex gap-3">
            <a href="/shop" class="cart-btn">Продолжить покупки</a>
            {% with cart_quantity=cart|length %}
            {% if cart_quantity  > 0%}
                <a href="#" class="cart-btn">Оформить заказ</a>
            {% endif %}
            {% endwith %}         
        </div>
    </section>


{% endblock content %}

NY_Shop/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>

        {% comment %} bootstrap {% endcomment %}
    <link rel="stylesheet" href="{% static 'bootstrap\css\bootstrap.min.css' %}">

        {% comment %} css {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    <header class="header sticky-top">
        
        <div class="header-container d-flex">

            <div class="header-logo">
                <a href="/"><img src="{% static 'img/logo.jpg' %}" alt="" class="ny-logo"></a>
            </div>
            <navbar class="header-nav pt-4">
               <ul class="header-list d-flex">
                <li>
                    <a href="/shop" class="nav-a m-3">Товары</a>
                </li>
                <li>
                    <a href="#" class="nav-a m-3">Скидки</a>
                </li>
               
                <li>
                    <a href="#" class="nav-a m-3">Контакты</a>
                </li>
               </ul> 
            </navbar>

            
            <div class="header-profile">
                <a href="{% url "cart:cart_detail" %}"><img src="{% static 'img/cart.png' %}" class="cart-img" alt="" width="70px"></a>
                
                <p class="cart_quantity">
                {% with cart_quantity=cart|length %}
                    {% if cart_quantity  > 0%}
                        {{ cart_quantity}}
                    {% else %}
                        0
                    {% endif %}
                {% endwith %}         
                </p>
            </div>


        </div>
    </header>
    
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>

    {% comment %} js for bootstrap {% endcomment %}
    <script src="{% static 'bootstrap\js\bootstrap.bundle.min.js' %}"></script>
</body>
</html>

NY_Shop/main/templates/main/index/index.html
{% extends "main/base.html" %}
{% load static%}
{% block title %}Главная страница{% endblock title %}



{% block content%}
    <section class="home d-flex flex-column">
        <div class="home-title">
            <a href="#" class="home-btn mt-4">Все товары</a>
        </div>
        <div class="home-recomendation">
            <div class="rec-title">
                <h3><span>Лидеры продаж</span></h3>
            </div>
        </div>
        <div class="home-cards">
            {% for product in products %}
                <a href="{{ product.get_absolute_url }}" class="home-card">
                    
                    <h5 class="title-card"> {{ product.name }} </h5>
                    <img src="{{ product.image.url }}" alt="" class="card-img">
                    {% if product.discount %}
                        <div class="card-discount">
                            <p class="line">{{ product.price }} ₽</p>
                            <p>{{ product.sell_price }} ₽</p>
                        </div>
                    {% else %}
                        <p class="price">{{ product.price }} ₽</p>
                        {% comment %} <btn class="+">+</btn> {% endcomment %}
                    {% endif %}
                </a>
                    
            {% endfor %}
        </div>
    </section>
    {% comment %} <img src="{% static 'img/logo.png' %}" alt="" class="logoindex"> {% endcomment %}
    {% comment %} <img src="{% static 'img/logo.png' %}" alt="" class="logoindex"> {% endcomment %}
{% endblock content %}

NY_Shop/main/templates/main/product/detail.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
    {{ product.name }}
{% endblock title %}

{% block content %}
    <div class="detail-product">
        <div class="detail-img">
            <img src="{% if product.image %}{{ product.image.url }}{% endif %}" alt="" class="detail-image" height="400" width="400">
        </div>
        <div class="detail-description">
            <h2>{{ product.name }}</h2>
            <h3>Категория: {{ product.category }}</h3>
            <p>Описание: {{ product.description|linebreaks }}</p>
            
            {% if product.discount %}
                <div class="cart-discount">
                    <p class="line">{{ product.price }} ₽</p>
                    <p>{{ product.sell_price }} ₽</p>
                </div>
            {% else %}
                <p class="price">{{ product.price }} ₽</p>
            {% endif %}
            
            <form action="{% url "cart:cart_add" product.id %}" class="qform" method="post">
                <div class="cart-form">
                    {{ cart_product_form }}
                    {% csrf_token %}
                </div>
                <input type="submit" class="add-to-cart-btn" value="Добавить в корзину">
            </form>
        </div>
    </div>
{% endblock content %}

NY_Shop/main/templates/main/product/list.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Shop{% endblock title %}

{% block content %}
    <div class="list">
        <div class="sidebar">
            <h3>Категории</h3>
            <ul>
                <li {% if not category %}class="selected"{% endif %}>
                    <a href="{% url "main:product_list" %}">Все товары</a>
                </li>
                {% for c in categories %}
                    <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                        <a href="{{ c.get_absolute_url}}">{{ c.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>

        <div class="main">
            <div class="main-title">
                {% if category %}{{ category.name}}{%else%}Товары{% endif %}
            </div>
            <div class="product-list">
                <div class="item">
                    {% for product in products %}
                        <div class="item">
                            <a href="{{product.get_absolute_url}}" class="home-card">
                                <h5 class="title-card">{{product.name}}</h5>
                                <img src="{{ product.image.url }}" alt="" class="card-img">
                                {% if product.discount %}
                                    <div class="card-discount">
                                        <p class="line">{{ product.price }} ₽</p>
                                        <p>{{ product.sell_price }} ₽</p>
                                    </div>
                                {% else %}
                                    <p class="price">{{ product.price }} ₽</p>
                                {% endif %}
                            </a> 
                        </div>
                    
                    {% endfor %}
                </div>
            </div>
       
            <ul class="pagination">
                <li class="{% if not products.has_previous %}disabled{% endif %}">
                    <a href="{% if products.has_previous %}?page={{ products.previous_page_number }}{% endif %}">Назад</a>
                </li>
                {% for page in products.paginator.page_range %}
                    {% if page >= products.number|add:-2 and page <= products.number|add:2 %}
                        <li>
                            <a href="?page={{ page }}" class="{% if products.number == page %}disabled{% endif %}">{{ page }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
                <li class="{% if not products.has_next %}disabled{% endif %}">
                    <a href="{% if products.has_next %}?page={{ products.next_page_number }}{% endif %}">Далее</a>
                </li>
            </ul>
        </div>
    </div>

{% endblock content %}